name: Eleventy Build
on: 
  push:
    branches:
      - master
    paths-ignore:
      - README.md
jobs:
  build-deploy:
    name: Eleventy Build
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Set up NPM
        uses: actions/setup-node@v2
        with:
          node-version: '22.16.0'
      - run: npm install
      - run: npm run sass
      - name: Build
        uses: TartanLlama/actions-eleventy@master
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
